name: Build RPM and DEB Packages

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm dpkg-dev

    - name: Set up environment for RPM
      run: |
        mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        
    - name: Prepare source for RPM
      run: |
        mkdir FileCounter-1.0
        cp count_files.sh FileCounter-1.0/
        tar -czvf ~/rpmbuild/SOURCES/FileCounter-1.0.tar.gz FileCounter-1.0

    - name: Create RPM SPEC file
      run: |
        cat << EOF > ~/rpmbuild/SPECS/FileCounter.spec
        Name: FileCounter
        Version: 1.0
        Release: 1%{?dist}
        Summary: A simple shell script to count files in /etc
        License: MIT
        Source0: %{name}-%{version}.tar.gz
        
        %description
        This package contains a shell script for counting files in the /etc directory.
        
        %prep
        %setup -q
        
        %build
        
        %install
        mkdir -p %{buildroot}/usr/bin
        install -m 755 count_files.sh %{buildroot}/usr/bin/count_files.sh
        
        %files
        /usr/bin/count_files.sh
        
        %changelog
        EOF

    - name: Build RPM package
      run: |
        rpmbuild -ba ~/rpmbuild/SPECS/FileCounter.spec

    - name: Create DEB structure
      run: |
        mkdir -p ~/FileCounter_1.0-1/usr/bin
        cp count_files.sh ~/FileCounter_1.0-1/usr/bin/
        mkdir ~/FileCounter_1.0-1/DEBIAN

    - name: Create DEB control file
      run: |
        cat << EOF > ~/FileCounter_1.0-1/DEBIAN/control
        Package: FileCounter
        Version: 1.0-1
        Section: utils
        Priority: optional
        Architecture: all
        Maintainer: Ivan <vanya1205root@example.com>
        Description: A simple shell script to count files in /etc
         This package contains a shell script for counting files in the /etc directory.
        EOF

    - name: Set permissions for DEB
      run: |
        chmod 755 ~/FileCounter_1.0-1/usr/bin/count_files.sh

    - name: Build DEB package
      run: |
        dpkg-deb --build ~/FileCounter_1.0-1

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ github.run_number }}"  # Можно заменить на версию вашего пакета
        release_name: "Release ${{ github.run_number }}"
        draft: false
        prerelease: false

    - name: Upload RPM to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ~/rpmbuild/RPMS/x86_64/file-counter-1.0-1.x86_64.rpm
        asset_name: file-counter-1.0-1.x86_64.rpm
        asset_content_type: application/x-rpm

    - name: Upload DEB to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ~/FileCounter_1.0-1.deb
        asset_name: file-counter-1.0-1.deb
        asset_content_type: application/x-debian-package
